# Generated by Django 4.0 on 2022-05-28 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pic', models.ImageField(upload_to='img/')),
                ('description', models.TextField()),
                ('image_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gallery.category')),
                ('image_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gallery.location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
